name: Deploy to EC2

on:
  push:
    branches:
      - main  # Triggers the workflow anytime code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2 via rsync
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets::EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets::EC2_HOST }}
        REMOTE_USER: ${{ secrets::EC2_USER }}
        TARGET: /var/www/jackstuehler.com/     # Change this to his exact Nginx folder path
        SOURCE: "./"                            # Syncs everything from the repo root
        ARGS: "-rlgoDIVzz --delete"             # Syncs files and deletes old ones on the server not in Git
